In [1]:
import numpy as np
import pandas as pd
import random

 ## 【問題1】train_test_splitのスクラッチ
スクラッチの練習として、scikit-learnのtrain_test_splitを自作してみます。以下の雛形をベースとして関数を完成させてください。

sklearn.model_selection.train_test_split — scikit-learn 0.21.3 documentation

なお、作成した関数がscikit-learnのtrain_test_splitと同じ動作をしているか必ず確認をするようにしましょう。

In [31]:
housing = pd.read_csv("/Users/tazawanaoki/diveintocode-ml/house-prices-advanced-regression-techniques/train.csv")

In [32]:
X = np.array(housing.drop("SalePrice", axis=1))
y = np.array(housing["SalePrice"])

In [47]:
X = housing.drop("SalePrice", axis=1)
y = housing["SalePrice"]

In [112]:
X[:10]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   
5   6          50       RL         85.0    14115   Pave   NaN      IR1   
6   7          20       RL         75.0    10084   Pave   NaN      Reg   
7   8          60       RL          NaN    10382   Pave   NaN      IR1   
8   9          50       RM         51.0     6120   Pave   NaN      Reg   
9  10         190       RL         50.0     7420   Pave   NaN      Reg   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC  Fence  \
0         Lvl    AllPub      ...                 0        0    NaN    NaN   
1         Lvl    AllPub      ...                 0        0    NaN    NaN   
2         Lvl    AllPub      ...                 0        0    NaN    NaN   
3         Lvl    AllPub      ...                 0        0    NaN    NaN   
4         Lvl    AllPub      ...                 0        0    NaN    NaN   
5         Lvl    AllPub      ...                 0        0    NaN  MnPrv   
6         Lvl    AllPub      ...                 0        0    NaN    NaN   
7         Lvl    AllPub      ...                 0        0    NaN    NaN   
8         Lvl    AllPub      ...                 0        0    NaN    NaN   
9         Lvl    AllPub      ...                 0        0    NaN    NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      2    2008        WD         Normal  
1         NaN       0      5    2007        WD         Normal  
2         NaN       0      9    2008        WD         Normal  
3         NaN       0      2    2006        WD        Abnorml  
4         NaN       0     12    2008        WD         Normal  
5        Shed     700     10    2009        WD         Normal  
6         NaN       0      8    2007        WD         Normal  
7        Shed     350     11    2009        WD         Normal  
8         NaN       0      4    2008        WD        Abnorml  
9         NaN       0      1    2008        WD         Normal  

[10 rows x 80 columns]

In [113]:
y[:10]

0    208500
1    181500
2    223500
3    140000
4    250000
5    143000
6    307000
7    200000
8    129900
9    118000
Name: SalePrice, dtype: int64

In [48]:
type(housing)

pandas.core.frame.DataFrame

In [79]:
def scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0):
    if type(X) != np.ndarray:
        X = np.array(X)
    if type(y) != np.ndarray:
        y = np.array(y)
    
    random.seed(seed)
    list_i = [i for i in range(X.shape[0])]
    random.shuffle(list_i)
    rnd_X = X[list_i]
    rnd_y = y[list_i]
    size = round(X.shape[0] * train_size)
    X_train, X_test = np.split(rnd_X, [size])
    y_train, y_test = np.split(rnd_y, [size])
    
    return X_train, X_test, y_train, y_test

In [90]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=5)

In [101]:
X_train.shape

(1168, 80)

In [102]:
X_test

array([[1103, 20, 'RL', ..., 2007, 'WD', 'Family'],
       [1155, 60, 'RL', ..., 2008, 'WD', 'Normal'],
       [839, 20, 'RL', ..., 2008, 'WD', 'Normal'],
       ...,
       [735, 20, 'RL', ..., 2007, 'WD', 'Family'],
       [524, 60, 'RL', ..., 2007, 'New', 'Partial'],
       [1276, 90, 'RL', ..., 2007, 'WD', 'Normal']], dtype=object)

In [103]:
X_test.shape

(292, 80)

In [99]:
y_train

array([178740, 226000, 230000, ..., 135900, 132000, 212000])

In [108]:
y_train[:10]

array([178740, 226000, 230000, 145000, 168000, 112500, 315500, 380000,
       108000, 135000])

In [104]:
y_train.shape

(1168,)

In [109]:
y_test[:10]

array([135000, 201800, 144000, 152000,  73000, 275000, 275000, 176000,
       260000, 155000])

In [39]:
y_train.shape

(1168,)

In [110]:
y_train[:10]

array([178740, 226000, 230000, 145000, 168000, 112500, 315500, 380000,
       108000, 135000])

In [111]:
y_test.shape

(292,)

 ## 【問題2】 分類問題を解くコードの作成
上記3種類の手法で3種類のデータセットを学習・推定するコードを作成してください。
 - ロジスティック回帰
 - SVM
 - 決定木

In [114]:
from sklearn.datasets import load_iris
iris = load_iris()

In [150]:
iris_X = iris.data[50:]
iris_y = iris.target[50:]

In [151]:
iris_y = np.where(iris_y == 1, 0, 1)
iris_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [165]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [166]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [175]:
print(linear_model.SGDRegressor())

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=None, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)


In [177]:
from sklearn import linear_model

clf = linear_model.SGDRegressor(loss='log')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

ValueError: The loss log is not supported. 

In [171]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
正解率:0.75
適合率:0.8
再現率:0.8
F値 :0.8000000000000002
[[2 1]
 [1 4]]


In [173]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')
正解率:0.875
適合率:1.0
再現率:0.8
F値 :0.888888888888889
[[3 0]
 [1 4]]


In [181]:
import numpy as np

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

In [182]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [183]:
clf = linear_model.SGDRegressor(loss='log')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

ValueError: The loss log is not supported. 

In [185]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
正解率:1.0
適合率:1.0
再現率:1.0
F値 :1.0
[[47  0]
 [ 0 53]]


In [186]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')
正解率:1.0
適合率:1.0
再現率:1.0
F値 :1.0
[[47  0]
 [ 0 53]]


In [225]:
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [226]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [227]:
clf = linear_model.SGDRegressor(loss=log)
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

NameError: name 'log' is not defined

In [228]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
正解率:0.75
適合率:0.8
再現率:0.8
F値 :0.8000000000000002
[[2 1]
 [1 4]]


In [231]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')
正解率:0.875
適合率:1.0
再現率:0.8
F値 :0.888888888888889
[[3 0]
 [1 4]]


 ## 【問題3】 回帰問題を解くコードの作成
線形回帰でHouse Pricesデータセットを学習・推定するコードを作成してください。

In [232]:
housing = pd.read_csv("/Users/tazawanaoki/diveintocode-ml/house-prices-advanced-regression-techniques/train.csv")

In [233]:
X = housing[["GrLivArea", "YearBuilt"]]
X.head()

GrLivArea  YearBuilt
0       1710       2003
1       1262       1976
2       1786       2001
3       1717       1915
4       2198       2000

In [234]:
y = housing["SalePrice"]
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [235]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [236]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [238]:
clf = linear_model.SGDRegressor()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(clf)
print("平均絶対誤差 (MAE):{}".format(mean_absolute_error(y_test, y_pred)))
print("平均二乗誤差 (MSE):{}".format(mean_squared_error(y_test, y_pred)))
print("二乗平均平方根誤差 (RMSE):{}".format(np.sqrt(mean_squared_error(y_test, y_pred))))
print("決定係数 (R**2) :{}".format(r2_score(y_test, y_pred)))

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=None, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)
平均絶対誤差 (MAE):4926259270066553.0
平均二乗誤差 (MSE):3.001082499718281e+31
二乗平均平方根誤差 (RMSE):5478213668449124.0
決定係数 (R**2) :-5.695882596238479e+21


/Users/tazawanaoki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
