In [1]:
import numpy as np
import pandas as pd
import random

 ## 【問題1】train_test_splitのスクラッチ
スクラッチの練習として、scikit-learnのtrain_test_splitを自作してみます。以下の雛形をベースとして関数を完成させてください。

sklearn.model_selection.train_test_split — scikit-learn 0.21.3 documentation

なお、作成した関数がscikit-learnのtrain_test_splitと同じ動作をしているか必ず確認をするようにしましょう。

In [2]:
housing = pd.read_csv("/Users/naoki/train.csv")

In [3]:
X = np.array(housing.drop("SalePrice", axis=1))
y = np.array(housing["SalePrice"])

In [4]:
X = housing.drop("SalePrice", axis=1)
y = housing["SalePrice"]

In [5]:
X[:10]

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   
5   6          50       RL         85.0    14115   Pave   NaN      IR1   
6   7          20       RL         75.0    10084   Pave   NaN      Reg   
7   8          60       RL          NaN    10382   Pave   NaN      IR1   
8   9          50       RM         51.0     6120   Pave   NaN      Reg   
9  10         190       RL         50.0     7420   Pave   NaN      Reg   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
2         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
5         Lvl    AllPub  ...           0        0    NaN  MnPrv        Shed   
6         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
7         Lvl    AllPub  ...           0        0    NaN    NaN        Shed   
8         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
9         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      2    2008        WD         Normal  
1       0      5    2007        WD         Normal  
2       0      9    2008        WD         Normal  
3       0      2    2006        WD        Abnorml  
4       0     12    2008        WD         Normal  
5     700     10    2009        WD         Normal  
6       0      8    2007        WD         Normal  
7     350     11    2009        WD         Normal  
8       0      4    2008        WD        Abnorml  
9       0      1    2008        WD         Normal  

[10 rows x 80 columns]

In [6]:
y[:10]

0    208500
1    181500
2    223500
3    140000
4    250000
5    143000
6    307000
7    200000
8    129900
9    118000
Name: SalePrice, dtype: int64

In [7]:
type(housing)

pandas.core.frame.DataFrame

In [8]:
def scratch_train_test_split(X = X, y = y, train_size = 0.8,seed = 0):
    if type(X) != np.ndarray:
        X = np.array(X)
    if type(y) != np.ndarray:
        y = np.array(y)
    
    random.seed(seed)
    list_i = [i for i in range(X.shape[0])]
    random.shuffle(list_i)
    rnd_X = X[list_i]
    rnd_y = y[list_i]
    size = round(X.shape[0] * train_size)
    X_train, X_test = np.split(rnd_X, [size])
    y_train, y_test = np.split(rnd_y, [size])
    
    return X_train, X_test, y_train, y_test

In [9]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=5)

In [10]:
X_train.shape

(1168, 80)

In [11]:
X_test

array([[1103, 20, 'RL', ..., 2007, 'WD', 'Family'],
       [1155, 60, 'RL', ..., 2008, 'WD', 'Normal'],
       [839, 20, 'RL', ..., 2008, 'WD', 'Normal'],
       ...,
       [735, 20, 'RL', ..., 2007, 'WD', 'Family'],
       [524, 60, 'RL', ..., 2007, 'New', 'Partial'],
       [1276, 90, 'RL', ..., 2007, 'WD', 'Normal']], dtype=object)

In [12]:
X_test.shape

(292, 80)

In [13]:
y_train

array([178740, 226000, 230000, ..., 135900, 132000, 212000])

In [14]:
y_train[:10]

array([178740, 226000, 230000, 145000, 168000, 112500, 315500, 380000,
       108000, 135000])

In [15]:
y_train.shape

(1168,)

In [16]:
y_test[:10]

array([135000, 201800, 144000, 152000,  73000, 275000, 275000, 176000,
       260000, 155000])

In [17]:
y_train.shape

(1168,)

In [18]:
y_train[:10]

array([178740, 226000, 230000, 145000, 168000, 112500, 315500, 380000,
       108000, 135000])

In [19]:
y_test.shape

(292,)

 ## 【問題2】 分類問題を解くコードの作成
上記3種類の手法で3種類のデータセットを学習・推定するコードを作成してください。
 - ロジスティック回帰
 - SVM
 - 決定木

In [20]:
from sklearn.datasets import load_iris
iris = load_iris()

In [21]:
iris_X = iris.data[50:]
iris_y = iris.target[50:]

In [22]:
iris_y = np.where(iris_y == 1, 0, 1)
iris_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [24]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X = iris_X, y = iris_y, train_size=0.8,seed=0)

In [25]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="log")
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
正解率:0.65
適合率:0.5882352941176471
再現率:1.0
F値 :0.7407407407407407
[[ 3  7]
 [ 0 10]]


In [26]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
正解率:0.9
適合率:0.8333333333333334
再現率:1.0
F値 :0.9090909090909091
[[ 8  2]
 [ 0 10]]


/Users/naoki/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [27]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
正解率:0.9
適合率:0.8333333333333334
再現率:1.0
F値 :0.9090909090909091
[[ 8  2]
 [ 0 10]]


In [28]:
import numpy as np

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

In [29]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [30]:


clf = SGDClassifier(loss="log")
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
正解率:1.0
適合率:1.0
再現率:1.0
F値 :1.0
[[47  0]
 [ 0 53]]


In [31]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
正解率:1.0
適合率:1.0
再現率:1.0
F値 :1.0
[[47  0]
 [ 0 53]]


/Users/naoki/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [32]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
正解率:1.0
適合率:1.0
再現率:1.0
F値 :1.0
[[47  0]
 [ 0 53]]


In [33]:
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [35]:
clf = SGDClassifier(loss="log")
# clf = linear_model.SGDRegressor()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
正解率:0.5
適合率:0.6666666666666666
再現率:0.4
F値 :0.5
[[2 1]
 [3 2]]


In [36]:
clf = SVC()
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)
正解率:0.75
適合率:0.8
再現率:0.8
F値 :0.8000000000000002
[[2 1]
 [1 4]]


/Users/naoki/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [37]:
clf = DecisionTreeClassifier(random_state=0, criterion='gini')
clf.fit(X_train, y_train)
clf_pred = clf.predict(X_test)
print(clf)
print("正解率:{}".format(clf.score(X_test, y_test)))
print("適合率:{}".format(precision_score(y_test,clf_pred)))
print("再現率:{}".format(recall_score(y_test,clf_pred)))
print("F値 :{}".format(f1_score(y_test,clf_pred)))
print(confusion_matrix(y_test,clf_pred))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')
正解率:0.875
適合率:1.0
再現率:0.8
F値 :0.888888888888889
[[3 0]
 [1 4]]


 ## 【問題3】 回帰問題を解くコードの作成
線形回帰でHouse Pricesデータセットを学習・推定するコードを作成してください。

In [38]:
housing = pd.read_csv("/Users/naoki/train.csv")

In [39]:
X = housing[["GrLivArea", "YearBuilt"]]
X.head()

GrLivArea  YearBuilt
0       1710       2003
1       1262       1976
2       1786       2001
3       1717       1915
4       2198       2000

In [40]:
y = housing["SalePrice"]
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [41]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X=X, y=y, train_size=0.8,seed=0)

In [42]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [44]:
from sklearn import linear_model

clf = linear_model.SGDRegressor()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(clf)
print("平均絶対誤差 (MAE):{}".format(mean_absolute_error(y_test, y_pred)))
print("平均二乗誤差 (MSE):{}".format(mean_squared_error(y_test, y_pred)))
print("二乗平均平方根誤差 (RMSE):{}".format(np.sqrt(mean_squared_error(y_test, y_pred))))
print("決定係数 (R**2) :{}".format(r2_score(y_test, y_pred)))

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)
平均絶対誤差 (MAE):746680295157462.1
平均二乗誤差 (MSE):6.831962383816335e+29
二乗平均平方根誤差 (RMSE):826556857319345.9
決定係数 (R**2) :-1.2966673073395473e+20
