 # 【問題1】SimpleRNNのフォワードプロパゲーション実装
SimpleRNNのクラスSimpleRNNを作成してください。基本構造はFCクラスと同じになります。

フォワードプロパゲーションの数式は以下のようになります。ndarrayのshapeがどうなるかを併記しています。

バッチサイズをbatch_size、入力の特徴量数をn_features、RNNのノード数をn_nodesとして表記します。活性化関数はtanhとして進めますが、これまでのニューラルネットワーク同様にReLUなどに置き換えられます。

In [1]:
class SimpleInitializer:

    
    def __init__(self, sigma=0.01):
        self.sigma = sigma
        
        
    def W(self, n_nodes1, n_nodes2):
        np.random.seed(5)
        self.W = self.sigma * np.random.randn(n_nodes1, n_nodes2)
        return self.W
    
    
    def B(self, n_nodes2):
        np.random.seed(5)
        self.B = self.sigma * np.random.randn(n_nodes2)
        return self.B

In [5]:
class ScratchSimpleRNN:
    
    def __init__(self, n_nodes1, n_nodes2,  initializerm, optimizer):
        self.optimizer = optimizer
        self.n_nodes1 = n_nodes1
        self.n_nodes2 = n_nodes2
        self.initializer = initializer
        self.optimizer = optimizer

        self.W = self.initializer.W(self.n_nodes1, self.n_nodes2)
        self.Wh = self.initializer.W(self.n_nodes1, self.n_nodes2)
        self.B = self.initializer.B(self.n_nodes2)
            
        
        def forward(self, X, h_pre):
            t = np.dot(h_pre, self.Wh) + np.dot(X, self.H) + self.B
            h_next = np.tanh(t)
            self.cache = (X, h_prev, h_next)
            return h_next
        

 # 【問題2】小さな配列でのフォワードプロパゲーションの実験
小さな配列でフォワードプロパゲーションを考えてみます。

入力x、初期状態h、重みw_xとw_h、バイアスbを次のようにします。

ここで配列xの軸はバッチサイズ、系列数、特徴量数の順番です。

In [6]:
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (n_nodes, n_nodes)
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
b = np.array([1, 1, 1, 1]) # (n_nodes,)

In [9]:
def forward( X, W, h_pre, Wh,  B):
    t = np.dot(h_pre, Wh) + np.dot(X, W) + B
    h_next = np.tanh(t)
    return h_next

In [11]:
for i in range(3):
    print(x[:,i],"xx")
    h = forward(x[:,i],w_x,h,w_h,b)
    print(h)

[[0.01 0.02]] xx
[[0.76188798 0.76213958 0.76239095 0.76255841]]
[[0.02 0.03]] xx
[[0.792209   0.8141834  0.83404912 0.84977719]]
[[0.03 0.04]] xx
[[0.79494228 0.81839002 0.83939649 0.85584174]]


In [12]:
def forward_ex( X, W, h_pre, Wh,  B,):
    for i in range(X.shape[1]):
            t = np.dot(h_pre, Wh) + np.dot(X[:,i], W) + B
            h_pre = np.tanh(t)
    return h_pre

In [13]:
forward_ex(x,w_x,h,w_h,b)

array([[0.79513154, 0.81868106, 0.83976521, 0.85625949]])