 ## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

In [1]:
import numpy as np
a_ndarray = np.array(
    [[-1, 2, 3],
     [4, -5, 6],
     [7, 8, -9]])
b_ndarray = np.array(
    [[0, 2, 1], 
     [0, 2, -8], 
     [2, 9, -1]])

a_ndarray = [[A00, A01, A02],  [A10, A11, A12], [A20, A21, A22] 
<br>
b_ndarray = [[B00, B01, B02],  [B10, B11, B12], [B20, B21, B22] 
<br>
a_ndarray × b_ndarray = [[C00, C01, C02],  [C10, C11, C12], [C20, C21, C22] 
<br>
[[-1, 2, 3],[4, -5, 6],[7, 8, -9]] × [[0, 2, 1],  [0, 2, -8], [2, 9, -1]] = [[C00, C01, C02],  [C10, C11, C12], [C20, C21, C22] 
<br>
<br>
C00 = A00×B00+A01×B10+A02×B20 = (-1)×0+2×0+3×2 = 6
<br>
C01 = A00×B01+A01×B11+A02×B21 = (-1)×2+2×2+3×9 = 29
<br>
C02 = A00×B02+A01×B12+A02×C22 = (-1)×1+2×(-8)+3×(-1) = -20 
<br>
C10 = A10×B00+A11×B10+A12×B20  = 4×0+(-5)×0+6×2 = 12
<br>
C11 = A10×B01+A11×B11+A12×B21 = 4×2+(-5)×2+6×9 = 52
<br>
C12 = A10×B02+A11×B12+A12×C22 = 4×1+(-5)×(-8)+6×(-1) = 38
<br>
C20 = A20×B00+A21×B10+A22×B20 = 7×0+8×0+(-9)×2 = -18
<br>
C21 = A20×B01+A21×B11+A22×B21 = 7×2+8×2+(-9)×9 = -51
<br>
C22 = A20×B02+A21×B12+A22×C22 = 7×1+8×(-8)+(-9)×(-1) = -48
<br>
<br>
よって、
<br>
[[C01, C02, C03],  [C11, C12, C13], [C21, C22, C23] = [[  6  29 -20], [ 12  52  38], [-18 -51 -48]]

## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

numpy.matmul — NumPy v1.16 Manual

numpy.dot — NumPy v1.16 Manual

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

In [2]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
a_ndarray.dot(b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

 - 行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
 - 行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
 - 行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値を全て足し合わせる
数式で表すと

2
∑
k
=
0
 
a
0
,
k
b
k
,
0
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [5]:
ndarray_00 = a_ndarray[0,0] * b_ndarray[0,0] + a_ndarray[0,1] * b_ndarray[1,0] + a_ndarray[0,2] * b_ndarray[2,0] 
ndarray_01 = a_ndarray[0,0] * b_ndarray[0,1] + a_ndarray[0,1] * b_ndarray[1,1] + a_ndarray[0,2] * b_ndarray[2,1] 
ndarray_02= a_ndarray[0,0] * b_ndarray[0,2] + a_ndarray[0,1] * b_ndarray[1,2] + a_ndarray[0,2] * b_ndarray[2,2]   
ndarray_10 = a_ndarray[1,0] * b_ndarray[0,0] + a_ndarray[1,1] * b_ndarray[1,0] + a_ndarray[1,2] * b_ndarray[2,0]   
ndarray_11 = a_ndarray[1,0] * b_ndarray[0,1] + a_ndarray[1,1] * b_ndarray[1,1] + a_ndarray[1,2] * b_ndarray[2,1]  
ndarray_12= a_ndarray[1,0] * b_ndarray[0,2] + a_ndarray[1,1] * b_ndarray[1,2] + a_ndarray[1,2] * b_ndarray[2,2]  
ndarray_20 = a_ndarray[2,0] * b_ndarray[0,0] + a_ndarray[2,1] * b_ndarray[1,0] + a_ndarray[2,2] * b_ndarray[2,0]   
ndarray_21 = a_ndarray[2,0] * b_ndarray[0,1] + a_ndarray[2,1] * b_ndarray[1,1] + a_ndarray[2,2] * b_ndarray[2,1]   
ndarray_22= a_ndarray[2,0] * b_ndarray[0,2] + a_ndarray[2,1] * b_ndarray[1,2] + a_ndarray[2,2] * b_ndarray[2,2]   

answer_list =[ndarray_00, ndarray_01, ndarray_02, ndarray_10, ndarray_11, ndarray_12, ndarray_20, ndarray_21, ndarray_22]
answer_array = np.array(answer_list).reshape(a_ndarray.shape[0], b_ndarray.shape[1])
print(answer_array)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


 ## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である 
3
×
3
 の行列Cの各要素 
c
i
,
j
 は数式で表すと次のようになります。

c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス 
i
 や 
j
 を1増やすと、次の行や列に移ることができます。

In [6]:
def seki(x,y):
    ans = []
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            for k in range(x.shape[1]):
                ans.append(x[i,k] * y[k,j])
    answer_list = [sum(ans[i:i+x.shape[1]]) for i in range(0,len(ans),x.shape[1])]
    answer_array = np.array(answer_list).reshape(x.shape[0], y.shape[1])
    print(answer_array)

In [7]:
seki(a_ndarray, b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [8]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [9]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [10]:
seki(a_ndarray, b_ndarray)

[[  6  29 -20]
 [ 12  52  38]]


In [11]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38]])

In [12]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2],
                                      [0, 2], 
                                      [2, 9]])

In [24]:
seki(a_ndarray, b_ndarray)

[[  6  29]
 [ 12  52]
 [-18 -51]]


In [14]:
a_ndarray @ b_ndarray

array([[  6,  29],
       [ 12,  52],
       [-18, -51]])

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [15]:
def seki_2(x,y):
    if x.shape[0] != y.shape[1]:
        print("※ 第一引数の列数と第二引数の行数が異なるため、行列の積は定義できません")
    else:
        ans = []
        for i in range(x.shape[0]):
            for j in range(y.shape[1]):
                for k in range(x.shape[1]):
                    ans.append(x[i,k] * y[k,j])
        answer_list = [sum(ans[i:i+x.shape[1]]) for i in range(0,len(ans),x.shape[1])]
        answer_array = np.array(answer_list).reshape(x.shape[0], y.shape[1])
        print(answer_array)

In [16]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [18]:
seki_2(d_ndarray,e_ndarray)

※ 第一引数の列数と第二引数の行数が異なるため、行列の積は定義できません


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [19]:
seki_2(d_ndarray.T,e_ndarray)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


In [21]:
seki_2(np.transpose(d_ndarray),e_ndarray)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


In [22]:
d_ndarray.T @ e_ndarray

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

In [23]:
np.transpose(d_ndarray) @ e_ndarray

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])